sudo: false
language: generic
jdk:
  - openjdk8
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    - TERM=dumb
    - GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m"
    - NDK_BUILD_PARALLEL=2
  matrix:
    - NDK_BUILD_ABI=arm64-v8a
    - NDK_BUILD_ABI=armeabi-v7a
    - NDK_BUILD_ABI=x86
    - NDK_BUILD_ABI=x86_64
addons:
  apt:
    packages:
     - lib32stdc++6
     - lib32z1
     - lib32z1-dev
     - build-essential
     - wget
     - unzip
before_install:
  - travis_retry .jenkins.d/10-get-sdk.sh
  - gem install rugged
  - travis_retry .jenkins.d/20-get-ndk.sh
script:
  - git submodule update --init --recursive
  - ./gradlew assembleDebug
